### ISSUE TITLE
Pure Special Edition - Not all DLC content is available

### ISSUE THREAD

**Issue by Fierelier** [NR74W/WipEout-Mods#11]
Some DLC content is missing, like ships, menu backgrounds and music. [I got all (?) EU DLCs from here](https://www.dropbox.com/scl/fo/b4l1p1kun8r3a89uxt27t/AM7s5aWxc8WjO6FHSLKo0qg?rlkey=wd4w8pne5tc2movmzmaataoc1) (**Careful!!** This upload is bad and also includes savedata!!)

I would love to see the Omega Pack skins, Voice of Cod music, and the ships from the Omega Ship Pack.

Thanks for modding one of my favorite PSP titles :)

**Comment by Fierelier** [comment]
I was able to get the Voice of Cod music in my game, by renaming `UCES00001DVOCMUSIC` to `WPSE02197DVOCMUSIC`. Seems to cause no trouble on my PSP :)

**Comment by NR74W** [comment]
WPSE already has every content ever released for WipEout Pure, it is useless to add any of the official DLC (may introduce issues).
Most of the DLC were promotional content, they are disabled by default in the mod because there were complaints in the past about the promo ships and DLC music, so it was made optional instead.
The promotional content can be enabled simply by adding a small DLC:
![README](https://github.com/user-attachments/assets/5750bdc1-576f-4cd5-a0c3-949cde9c5c5e)

**Comment by Fierelier** [comment]
I actually read that note, but could not see the file, because I had assumed it was larger :D -- Thank you!
