### ISSUE TITLE
Bug - Bad FMV Playback on Adrenaline

### ISSUE THREAD

**Issue by ThatOneBonk** [NR74W/WipEout-Mods#4]
When playing back FMVs in the frontend, the video can be choppy, slow or laggy, it can freeze, the audio is choppy and can freeze.
I have confirmed that this bug is introduced by applying the WPSE 5 patch, that the patch has been applied correctly, the ISO file was transferred properly and that this issue is reproducible on my setup (Vita 1K Adrenaline).
FMVs affected:
- Pre-Language Selection FMV (Minor; might be because of background load operations introduced in WPSE)
- Intro FMV (Serious)

**Comment by NR74W** [comment]
At the time I didn't test the hack on Vita because it worked correctly on a PSP, I had no idea it would behave differently on Vita, so thanks for reporting.

With the same setup (Vita 100x and Adrenaline), after looking into it:
The stuttery video playback issue is caused by playing FMV at 60FPS, even using the unmodified/original game on Vita. This bug can only be reproduced on Vita, as both the PSP 300x and PPSSPP plays the FMVs without stuttering.
The Media Engine is emulated on Vita, perhaps this explains why.

v5.2 was released with the framerate change reverted. 60FPS is enabled by default only on v5.2A (since it's only useful for PPSSPP).

**Comment by ThatOneBonk** [comment]
Thank you!
