### ISSUE TITLE
Shurikens and Repulsors in online play (FX350-4.0)

### ISSUE THREAD

**Issue by ThatOneBonk** [NR74W/WipEout-Mods#5]
WipEout Pulse FX350 Edition version 4.0 alters the pickup odds to include the Shuriken and Repulsor pickups in single races. 
This normally isn't an issue, however since infrastructure online play has been restored with the Beat project, players that use this version of the game have a significant unfair advantage over those who don't have access to the two additional weapons.
The Thallium+Beat team requests the pickup odds to be reverted to their vanilla values or infrastructure online play mode removed from the frontend.

**Comment by NR74W** [comment]
17 years after the release of the original game, the online part of the game is once again functional. I didn't foresee that the stupid mistake of making these weapons available in other modes would one day affect online play. I'm sorry for this mess.
I was planning to make a "Special Edition" for Pulse for a while now, but the last few weeks have been pretty busy and it took *way* longer than anticipated.

The mod was rebuilt from the ground up, updated and renamed to "WipEout Pulse: Future Edition 5.0 / 5.0E"... Front end improved, some small enhancements and a *much* smaller game size (5.0 = -277MB vs. 4.0A; 5.0E = -483MB vs. 4.0).
For v5.0E it seems the crash after a race in the Statistics menu screen and at the end of a race on Exostra Run doesn't occur anymore (for the Exostra one, it may be the exact same bug as in the original Pure... so it was a bad idea to use the soundbank file in Pulse as well) and perhaps more stable (no crashes encountered). The lens flares were also removed.

Efforts to make Altima VII and Porto Kora working correctly were all in vain, there is something that may be wrong at the end of the wo_track node but I can't even be sure, what's certain is that it's exactly the same location where the track ends prematurely. Understanding the VEXX format is necessary to fix the tracks but this is beyond my level.

The weapon change was reverted, at first I wanted to make Online play unavailable/non-functional and remove all mentions of online features, but there are people actually playing on Pure tracks online.
Now absolutely nothing impacting the gameplay is present in the mod, except for WPFE 5.0E: the Quake weapon is disabled because the 'Quake' node in the VEX v4 is not compatible with Pulse (otherwise it crashes instantly if this weapon is used on legacy tracks), so people playing this version will be disadvantaged against others who don't have it. Everything else are Quality-of-Life enhancements that have no effect in-game.
I could not test the online feature so I don't know if it works anymore.

**Comment by NR74W** [comment]
I had no idea the wipeout-game.com option could still be useful. It was removed because I thought it was obsolete and no longer served any purpose, I really apologize.
The patch was updated to v5.1 with the website and the original Presents screen restored in respect to the original work, sorry again. I will do the same with WPSE in v5.3 later.

**Comment by ThatOneBonk** [comment]
Thank you so much!
You didn't have to restore the Presents screen, by the way, for it is just my personal preference, but thank you for that too.
