### ISSUE TITLE
Request - Make the mods open source

### ISSUE THREAD

**Issue by ThatOneBonk** [NR74W/WipEout-Mods#7]
As it is, one can only download a finished mod and install it. If the assets that are composed into an .xdelta file were included, it would allow for greater flexibility on user's part.

**Comment by NR74W** [comment]
It is important to make things publicly available so that others can continue working on it, but it is rare to see mods with sources or anything else useful available, and users are generally ungrateful.

For full disclosure, the tools used are [wadutil](https://thp.io/2021/wadutil/)/[dlc2dlc](https://thp.io/2021/pure-dlc.html)/[vextextool](https://thp.io/2022/vextextool/) made by Thomas Perl (open-source and available on [GitLab](https://gitlab.com/thp) and [thp.io](https://thp.io/)) and TC/ttfextract from the Pulse PS2 disc (not FOSS).
There is not much to share about these mods, every files are contained in the Data.wad for both mods.

The full content itself cannot be distributed as it contains all data from the base game and the executable from the mod is also necessary to make it work, this would be no different from hosting the .iso directly in the repository. It would also take up space on the MEGA repository, which I also use for personal cloud storage.

Everything can be extracted successfully from the Data.wad of both modded games using wadutil, and the up-to-date filenames.txt from the [Documentation](https://mega.nz/folder/lMRVELoR#01a4KaUDbCycjlrDgq5UdQ/folder/oEpTCYwb) folder on MEGA.

**Comment by ThatOneBonk** [comment]
I see. Thanks for the heads up!
