### ISSUE TITLE
Feature Request - Modular implementation of WPFE and WPSE

### ISSUE THREAD

**Issue by ThatOneBonk** [NR74W/WipEout-Mods#8]
As it is, every time a mod is updated, one has to patch a vanilla ISO, put it on their console and replace the old one. A system could be implemented where a base ISO is created that is able to load custom DLCs, not unlike the current expert mode/promo packs etc., but for the entire mod. That way, minor updates won't require the user to replace the whole ISO, but instead just that one DLC.

**Comment by NR74W** [comment]
The current method of patch revision is indeed tedious, the DLC model you suggested would be far more convenient and easier to manage, but it has some limitations:

- Any changes made to content outside Data.wad is not possible (ex: EBOOT.BIN, like for restoring the Presents screen textures embedded in the executable).

- For some reasons I don't understand, if a custom DLC PI.WAD exceeds about 2 or 3MB, WipEout Pure can't read the content from that DLC and inevitably crashes when navigating in the menu (even a single track or music in the .wad is already too much). That's why all the custom DLC are very small and contain almost nothing, it was initially planned to move all promotional content (about 170MB) to the Promo DLC to reduce the disc size to a minimum but it was impossible.
Something must be wrong in the dlc2dlc source but I don't have the knowledge to figure out, WipEout Pulse is not affected by this limitation since this game supports only normal .wad files for DLC.

- The game loads a number of files from disc before loading downloadable content, but these same files cannot be replaced afterwards (track stats/records, fonts, and many others). It was impossible to make a custom font DLC for WipEout Pure instead of a patch, even for a small change like restoring the Online options in Pure was also only possible with a new xdelta patch.
The experimental version of WPFE using a DLC was theoretically possible... but the game just does not load the weaponstats XMLs from a DLC (which was critical for compatibility (quake issue)), so the idea was abandoned.
In case of a change affecting an important file (from XML/PI folders and perhaps others) or adding/replacing larger files (for Pure), the whole game needs to be patched since it won't load it from  DLC.

I don't have much left to offer so the burden of updates will come to an end very soon.

**Comment by ThatOneBonk** [comment]
Thank you for your reply! That's a shame.
